# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    twig.extension.intl:
      class: Twig_Extensions_Extension_Intl
      tags:
        - { name: twig.extension }
    import.csvtoarray:
            class: AppBundle\Service\Import\ConvertCsvToArray

    scorenco.scorenco_service:
      class: AppBundle\Service\Scorenco\ScorencoService

    licencie.licencie_service:
      class: AppBundle\Service\Licencie\LicencieService
      arguments: ["@doctrine.orm.entity_manager","@kernel"]

    app.statistiques_service:
      class: AppBundle\Service\StatistiquesService
      arguments: ["@kernel"]

    app.repository.produit_repository:
      class: AppBundle\Repository\ProduitRepository
      factory: 'Doctrine\ORM\EntityManagerInterface:getRepository'
      arguments:
        - AppBundle\Entity\Boutique\Produit

    app.boutique.panier.panier_service:
      class: AppBundle\Service\Boutique\Panier\PanierService
      arguments: ['@Symfony\Component\HttpFoundation\Session\SessionInterface', '@app.repository.produit_repository']


    app.generation_image_controller:
      class: AppBundle\Controller\GenerationImageController
      calls:
        - [setContainer, ["@service_container"]]

    app_core.facebook:
       # notre classe
       class: AppBundle\Service\ReseauxSociaux\FacebookService
       #  on ajoute nos identifiants en param√®tre
       arguments: ["%app_id%","%app_secret%","%page_id%","%token%"]
